---
steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/npm', '.']
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ["-c","gcloud secrets versions access latest --secret=StorjAPIKey >>secret.txt" ]
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'npm'
    args: ["install"]
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'bash'
    args: ["-c","make && node-gyp configure && node-gyp rebuild"]
  - name: 'gcr.io/${PROJECT_ID}/npm'
    entrypoint: 'npm'
    args: ["test"]
tags: ['cloud-builders-community']
images: ['gcr.io/$PROJECT_ID/npm']
tags: ['cloud-builders-community']
